apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jonas-service
  namespace: default
  labels:
    app:jonas-service
spec:
  replicas: 4
  selector:
    matchLabels:
      app: jonas-service
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
  template:
    metadata:
      labels:
        app: jonas-service
    spec:
      containers:
      - image: docker.io/jonasberlin/ci-demo:15
        imagePullPolicy: Always
        name: jonas-service
        ports:
        - containerPort: 8080

