kind: Deployment
apiVersion: apps/v1
metadata:
  name: image-recognizer
  namespace: default
  labels:
    app: image-recognizer
spec:
  replicas: 2
  minReadySeconds: 60
  selector:
    matchLabels:
      app: image-recognizer
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: image-recognizer
    spec:
      containers:
      - image: docker.io/jonasberlin/ci-demo:${BUILD_NUMBER}
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command: ["bash", "-c", "sleep 10"]
        name: image-recognizer-deployment
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          successThreshold: 1

