apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: image-recognizer
  namespace: default
  labels:
    app: image-recognizer
spec:
  replicas: 4
  minReadySeconds: 10
  selector:
    matchLabels:
      app: image-recognizer
    strategy:
      rollingUpdate:
        maxSurge: 25%
        maxUnavailable: 25%
      type: RollingUpdate
  template:
    metadata:
      labels:
        app: jonas-service
    spec:
      containers:
      - image: docker.io/jonasberlin/ci-demo:${BUILD_NUMBER}
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command: ["bash", "-c", "sleep 10"]
        name: jonas-service
        ports:
        - containerPort: 8080
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
