{
  "kind": "Ingress",
  "apiVersion": "extensions/v1beta1",
  "metadata": {
    "name": "image-recognition-ingress",
    "namespace": "default",
    "annotations": {
      "nginx.ingress.kubernetes.io/rewrite-target": "/",
      "nginx.ingress.kubernetes.io/ssl-redirect": "false"
    }
  },
  "spec": {
    "rules": [
      {
        "host": "theberlins.local",
        "http": {
          "paths": [
            {
              "backend": {
                "serviceName": "image-recognizer-deployment",
                "servicePort": 8080
              }
            }
          ]
        }
      }
    ]
  }
}

